export type Game = {
  id: number
  title: string
  provider: string
  img: string
  hot?: boolean
  category: "new" | "top" | "slots" | "live" | "crash"
}

export const games: Game[] = [
  {
    id: 1,
    title: "Royal Easter",
    provider: "BGaming",
    img: "/placeholder.svg?height=400&width=360",
    hot: true,
    category: "new",
  },
  {
    id: 2,
    title: "Sugar Merge Up",
    provider: "BGaming",
    img: "/placeholder.svg?height=400&width=360",
    category: "new",
  },
  {
    id: 3,
    title: "CULT.",
    provider: "Pragmatic",
    img: "/placeholder.svg?height=400&width=360",
    hot: true,
    category: "top",
  },
  {
    id: 4,
    title: "Mummyland Treasures",
    provider: "Belatra",
    img: "/placeholder.svg?height=400&width=360",
    category: "slots",
  },
  {
    id: 5,
    title: "Mummy Mines",
    provider: "Belatra",
    img: "/placeholder.svg?height=400&width=360",
    category: "slots",
  },
  {
    id: 6,
    title: "Olympus Rivals",
    provider: "Amigo",
    img: "/placeholder.svg?height=400&width=360",
    hot: true,
    category: "top",
  },
  {
    id: 7,
    title: "Sloteus Gold",
    provider: "Endorphina",
    img: "/placeholder.svg?height=400&width=360",
    category: "slots",
  },
  {
    id: 8,
    title: "Fruit Invaders",
    provider: "Amigo",
    img: "/placeholder.svg?height=400&width=360",
    category: "new",
  },
  {
    id: 9,
    title: "Crown Coins",
    provider: "Endorphina",
    img: "/placeholder.svg?height=400&width=360",
    category: "slots",
  },
  {
    id: 10,
    title: "Mummy's Jewels 100",
    provider: "Pragmatic",
    img: "/placeholder.svg?height=400&width=360",
    hot: true,
    category: "top",
  },
  {
    id: 11,
    title: "Sultans Fortune",
    provider: "KAGaming",
    img: "/placeholder.svg?height=400&width=360",
    category: "new",
  },
  {
    id: 12,
    title: "Gold Canyon",
    provider: "Betsoft",
    img: "/placeholder.svg?height=400&width=360",
    category: "slots",
  },
  {
    id: 13,
    title: "Raging Wings",
    provider: "Endorphina",
    img: "/placeholder.svg?height=400&width=360",
    category: "new",
  },
  {
    id: 14,
    title: "3 Crowns: Coin Hunt",
    provider: "Evoplay",
    img: "/placeholder.svg?height=400&width=360",
    category: "slots",
  },
  {
    id: 15,
    title: "Book of Crystal Fruits",
    provider: "Tomhorn",
    img: "/placeholder.svg?height=400&width=360",
    category: "slots",
  },
  {
    id: 16,
    title: "Zeus vs Hades",
    provider: "Pragmatic",
    img: "/placeholder.svg?height=400&width=360",
    hot: true,
    category: "top",
  },
  {
    id: 17,
    title: "Starlight Princess",
    provider: "Pragmatic",
    img: "/placeholder.svg?height=400&width=360",
    hot: true,
    category: "top",
  },
  {
    id: 18,
    title: "Bonanza Billion",
    provider: "BGaming",
    img: "/placeholder.svg?height=400&width=360",
    hot: true,
    category: "top",
  },
  {
    id: 19,
    title: "Aviator Crash",
    provider: "Spribe",
    img: "/placeholder.svg?height=400&width=360",
    hot: true,
    category: "crash",
  },
  {
    id: 20,
    title: "JetX",
    provider: "Smartsoft",
    img: "/placeholder.svg?height=400&width=360",
    category: "crash",
  },
  {
    id: 21,
    title: "Live Roulette VIP",
    provider: "Evolution",
    img: "/placeholder.svg?height=400&width=360",
    category: "live",
  },
  {
    id: 22,
    title: "Lightning Blackjack",
    provider: "Evolution",
    img: "/placeholder.svg?height=400&width=360",
    hot: true,
    category: "live",
  },
  {
    id: 23,
    title: "Crazy Time",
    provider: "Evolution",
    img: "/placeholder.svg?height=400&width=360",
    category: "live",
  },
  {
    id: 24,
    title: "Sweet Bonanza",
    provider: "Pragmatic",
    img: "/placeholder.svg?height=400&width=360",
    hot: true,
    category: "top",
  },
]

export const liveWins = [
  { user: "User***", amount: "5,200 ₽", game: "Gates of Olympus" },
  { user: "Alex***", amount: "12,400 ₽", game: "Sweet Bonanza" },
  { user: "Kira***", amount: "890 ₽", game: "Royal Easter" },
  { user: "Dim***", amount: "45,000 ₽", game: "Sugar Rush" },
  { user: "Mar***", amount: "2,150 ₽", game: "Aviator" },
  { user: "Lex***", amount: "8,400 ₽", game: "Zeus vs Hades" },
  { user: "Vov***", amount: "120,000 ₽", game: "Crazy Time" },
  { user: "Nik***", amount: "3,300 ₽", game: "Starlight Princess" },
  { user: "Ele***", amount: "17,900 ₽", game: "JetX" },
]
